packages:
  - "."
onlyBuiltDependencies:
  - esbuild
  - "@prisma/engines"
  - prisma
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@parcel/watcher"
  - "@swc/core"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': set this to true or false
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  vue-demi: true
